console_title_template = '{{ .Shell }} in {{ .PWD }}'
version = 3
final_space = true

[palette]
    blue = '#89B4FA'
    closer = 'p:os'
    lavender = '#B4BEFE'
    os = '#ACB0BE'
    pink = '#F5C2E7'
    red = '#F38BA8'

[secondary_prompt]
    template = 'â±â± '
    foreground = 'p:closer'
    background = 'transparent'

[transient_prompt]
    template = 'â± '
    foreground = ''
    background = 'transparent'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:closer{{end}}']

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        style = 'plain'
        template = '{{ .Path }} '
        foreground = 'p:pink'
        background = ''
        type = 'path'

        [blocks.segments.properties]
            folder_icon = '..ğŸ— ..'
            home_icon = '~'
            style = 'agnoster_short'

    [[blocks.segments]]
        style = 'plain'
        template = '{{ .HEAD }} '
        foreground = 'p:lavender'
        background = ''
        type = 'git'

        [blocks.segments.properties]
            branch_icon = 'îœ¥ '
            cherry_pick_icon = 'îŠ› '
            commit_icon = 'ï— '
            fetch_bare_info = true
            fetch_status = false
            fetch_upstream_icon = false
            merge_icon = 'îœ§ '
            no_commits_icon = 'ïƒƒ '
            rebase_icon = 'îœ¨ '
            revert_icon = 'ïƒ¢ '
            tag_icon = 'ï’ '

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        style = 'plain'
        template = 'â±'
        foreground = 'p:closer'
        background = ''
        type = 'text'
        foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:closer{{end}}']
